include(":dialog-fragment")
include(":fileprovider-camera:app")
include(":fileprovider-camera:appcrop")
include(":fileprovider-camera:camera")
include(":fonts")
include(":navigation")
include(":workmanager")
