name: CI

on: [ push ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: bash ./gradlew ktlintCheck detekt lint test build connectedAndroidTest --stacktrace

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
