name: CI

on: [ push ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: bash ./gradlew ktlintCheck detekt lint test build connectedAndroidTest --stacktrace
