name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: ci
      run: bash ./gradlew clean ktlint detekt build test connectedAndroidTest --stacktrace
